use anyhow::Error;

// phone.acceptCall
pub async fn phone_accept_call() -> Result<i32, Error> {
    Ok(1)
}

// phone.confirmCall
pub async fn phone_confirm_call() -> Result<i32, Error> {
    Ok(1)
}

// phone.discardCall
pub async fn phone_discard_call() -> Result<i32, Error> {
    Ok(1)
}

// phone.getCallConfig
pub async fn phone_get_call_config() -> Result<i32, Error> {
    Ok(1)
}

// phone.receivedCall
pub async fn phone_received_call() -> Result<i32, Error> {
    Ok(1)
}

// phone.requestCall
pub async fn phone_request_call() -> Result<i32, Error> {
    Ok(1)
}

// phone.saveCallDebug
pub async fn phone_save_call_debug() -> Result<i32, Error> {
    Ok(1)
}

// phone.sendSignalingData
pub async fn phone_send_signaling_data() -> Result<i32, Error> {
    Ok(1)
}

// phone.setCallRating
pub async fn phone_set_call_rating() -> Result<i32, Error> {
    Ok(1)
}

// phone.saveCallLog
pub async fn phone_save_call_log() -> Result<i32, Error> {
    Ok(1)
}

// messages.deletePhoneCallHistory
pub async fn messages_delete_phone_call_history() -> Result<i32, Error> {
    Ok(1)
}